version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  api:
    container_name: api-container
    image: node:latest
    working_dir: /usr/src/app
    restart: always
    ports:
      - 5050:5050
      - 9222:9222
    depends_on:
      - mongo
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./dist:/usr/src/app/dist
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017