version: "3"

services:
  mongo:
    container_name: mongo-container
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  api:
    container_name: api-container
    build: .
    restart: always
    ports:
      - 5050:5050
    depends_on:
      - mongo
    command: npm start
    volumes:
      - ./dist:/usr/src/app/dist
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017